---

- name: Install Java
  package:
    state=latest
    name={{ item }}
  with_items: "{{ blueflood_java_packages }}"

- name: Ensure User Exists
  useradd:
    user={{ blueflood_user }}
    group={{ blueflood_group }}
    home={{ blueflood_home }}

- name: Get Blueflood
  get_url:
    url=https://github.com/rackerlabs/blueflood/releases/download/rax-release-v{{ blueflood_version }}/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar
    dest={{ blueflood_home }}

- name: Make Blueflood Config Dir
  file:
    path={{ blueflood_home }}/config
    state=directory
    mode=0700
    owner={{ blueflood_user }}
    group={{ blueflood_group }}

- name: Install Blueflood Config
  template:
    src=blueflood.conf.j2
    dest={{ blueflood_home }}/config/blueflood.conf
    mode=0600
    owner={{ blueflood_user }}
    group={{ blueflood_group }}

- name: Install Blueflood Log4j Config
  template:
    src=blueflood-log4j.properties.j2
    dest={{ blueflood_home }}/config/blueflood-log4j.properties
    mode=0600
    owner={{ blueflood_user }}
    group={{ blueflood_group }}

- name: Make Blueflood Bin Dir
  file:
    path={{ blueflood_home }}/bin
    state=directory
    mode=0700
    owner={{ blueflood_user }}
    group={{ blueflood_group }}

- name: Install Start Script
  template:
    src=blueflood-run.j2
    dest={{ blueflood_home }}/bin/blueflood
    mode=0700
    owner={{ blueflood_user }}
    group={{ blueflood_group }}
